server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: yandex-lavka-25
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres # TODO Поменять название БДб порт
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
